categorie_work_index:
    path:     /
    methods:  [GET]
    defaults: { _controller: AdminBundle:Categories:indexCategorieWork }
    
categorie_work_new:
    path:     /new
    methods:  [GET, POST]
    defaults: { _controller: AdminBundle:Categories:newCategorieWork }
    