admin_categories:
    prefix:     /{token}/categories
    resource: "@AdminBundle/Resources/config/routes/categories.yml"

admin_dashboard:
    prefix:     /{token}
    resource: "@AdminBundle/Resources/config/routes/dashboard.yml"

admin_transport:
    prefix:     /{token}/transport
    resource: "@AdminBundle/Resources/config/routes/transport.yml"
