admin_dashboard:
    resource: "@AdminBundle/Resources/config/routes/dashboard.yml"

admin_transport:
    prefix:     /transport
    resource: "@AdminBundle/Resources/config/routes/transport.yml"
