gallery:
    resource: "@GalleryBundle/Resources/config/routing.yml"
    host:     "%gallery_domain%"

account:
    resource: "@AccountBundle/Resources/config/routing.yml"
    host:     "%account_domain%"

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    host:     "%admin_domain%"
